resources:
  - name: pipeline-example-repo
    type: git
    check_every: 1m
    source:
      uri: git@github.com:kirthiprakash/pipeline-example.git
      branch: master
      paths:
        - app

jobs:
  - name: stage-display-commit
    plan:
      - get: pipeline-example-repo
        version: every
        trigger: true
      - task: display-file
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: cat
            args: [pipeline-example-repo/file.txt]

